### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by diabl0w** [tkem/mopidy-podcast-itunes#10]
Is there supposed to be a terminal command or is something supposed to show up in the webui? I can't find any commands or anything on the webui.

**Comment by tkem** [comment]
After installation, this should be available for browsing (as root directory "iTunes Store: Podcasts") and searching, e.g. with the MPD frontend:
```
$ mpc ls
Files
Podcasts
iTunes Store: Podcasts
```
