### ISSUE TITLE
Wrong URI's

### ISSUE THREAD

**Issue by tilllt** [tkem/mopidy-podcast-itunes#12]
I can only load some few ITunes podcasts, most fail.

In this example it doesnt play (Track Details)

```
Not found
Could not find anything with URI podcast+http://clarkesworldmagazine.com/?feed=podcast%23http://clarkesworldmagazine.com/?p=842
```

This DOES play:

```
Not found
Could not find anything with URI podcast+https://www.rbb-online.de/rbbkultur/podcasts/schoene-neue-welt-podcast.xml/feed=podcast.xml%23https://rbbmediapmdp-a.akamaihd.net/content/89/b0/89b0f237-2110-49a7-a7cc-4338a8161f4b/8ea2fdf5-7e28-403f-af42-4808772e9206_2e980a50-48a5-4a4a-a5a3-a14eed22d5ea.mp3
```

is this extension abandoned, i see some very old open issues here...

**Comment by tkem** [comment]
@tilllt No, it's not abandoned, it's just considered "done" to some degree ;-)

If you're using the Iris client, this is probably similar to https://github.com/tkem/mopidy-podcast/issues/59.

In short, Iris (wrongly, IMHO) encodes "#" as "%23" in URIs, which breaks mopidy-podcast which breaks mopidy-podcast-itunes.

You may try a different client to verify this.

**Comment by tilllt** [comment]
Just for my understanding, why do you assume its wrong to encode "#" as %23 ... thats the offical way to encode the hash sign in urls: https://stackoverflow.com/questions/5007352/how-to-escape-hash-character-in-url

**Comment by tkem** [comment]
Please see https://github.com/jaedb/Iris/issues/713.
