### ISSUE TITLE
Error when searching with ncmpcpp

### ISSUE THREAD

**Issue by mountwebs** [tkem/mopidy-podcast-itunes#7]
When I do a search from ncmpcpp I get this error from Mopidy: "Error converting iTunes search result: Unsupported result type "song"" (I did not use the "song" search tag). Is there any way to fix this? I would love to be able to search with ncmpcpp and still use mopidy-podcast-itunes!

**Comment by mountwebs** [comment]
I resolved this issue in another way. Turns out that I just had to increase the timeout variable in ncmpcpp. There is still an error, but it doesn't matter.

My bad.

**Comment by tkem** [comment]
The error (which should probably be converted to a mere warning) just says that the search results from iTunes contained a "song" item; mopidy-podcast-itunes only handles/expects "podcast" and "podcast-episode" items, and will simply skip everything else. So this should not affect the client.
Anyway, the actual query you used would be interesting to reproduce this.
